[build]
  publish = "out"
  command = "npm run build"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/herovideo.mp4"
  [headers.values]
    Cache-Control = "public, max-age=604800"
    Content-Type = "video/mp4"

[[headers]]
  for = "/about hero.mp4"
  [headers.values]
    Cache-Control = "public, max-age=604800"
    Content-Type = "video/mp4"
